name: Anima Build and Deploy action
on:
  push:
    branches:
      - anima-v2-deploy
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Version Name (e.g. v2.0.0)'
        required: true
        default: 'v2.0.0'
      is_prerelease:
        description: 'Is this a Pre-release?'
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.11.0'
          arch: 'win64_mingw'

      - name: Configure CMake
        run: cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Bundle DLLs
        run: |
          windeployqt --qmldir . build/appAnima_Pro.exe

      - name: Create ZIP
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: 'build'
          filename: 'Anima-v2.zip'

      - name: Save Private Test Build
        uses: actions/upload-artifact@v4
        with:
          name: Private-Testing-Build
          path: build/Anima-v2.zip

      - name: Create Official Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_name }}
          name: Anima ${{ github.event.inputs.release_name }}
          body_path: CHANGELOG.md
          prerelease: ${{ github.event.inputs.is_prerelease }}
          files: build/Anima-v2.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}